trigger:
- unit-test

pool: ofqual-agent

variables:
  buildConfiguration: 'Release'

stages:
  - stage: build
    jobs:
    - job: 'build'
      steps:
      - task: UseDotNet@2
        displayName: 'Use DotNet 6'  
        inputs:
          packageType: 'sdk'
          version: '6.x'
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - script: |
          echo '{"sdk": {"version": "5.0.301"}}' > global.json
        displayName: 'Set global.json for SDK version'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet restore'
        inputs:
          command: restore
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet build'
        inputs:
          command: build
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet test'
        inputs:
          command: test
          projects: '**/*Test/*.csproj'
          arguments: '--configuration $(buildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet publish'
        inputs:
          command: publish
          publishWebProjects: True
          arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: True

      - task: PublishBuildArtifacts@1
        displayName: 'publish artifacts'
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'myWebsiteName'

