trigger:
- dev  # Trigger pipeline on changes to the main branch
variables:
- name: DOCKER_BUILDKIT
  value: 1
pool: ofqual-agent

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:  
    - job: Build
      displayName: Build job
      # pool:
      #   vmImage: 'windows-2019'
      steps:
      - checkout: self  # Checkout the repository
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: 'bola1.azurecr.io/frontend'  # ACR and image name
          dockerfile: '$(Build.SourcesDirectory)/Dockerfile'  # Path to Dockerfile
          containerRegistry: 'cgi-acr-connection'  # ACR name
          tags: |
            $(Build.BuildId)
            
 
